### PR TITLE
get cookie set in response on server side

### LINKED ISSUE #3: get cookie set in response on server side
currently .get is getting from request. It would be awesome if it can also take account of what has been set during the request on its response

### PR DESCRIPTION
**Pull request by goldensunliu**
fixes https://github.com/change/cookie-dough/issues/3

### CODE REVIEW

**Comment by goldensunliu** [comment]
@saponifi3d Let me know if this hack is okay for now.

**Comment by saponifi3d** [comment]
Awesome!  Thanks for the contribution!

This seems like a good, simple fix.  Can you add a test case for the getter and setter, and make sure ;'s are being used? Thanks!!

**Comment by goldensunliu** [comment]
@saponifi3d the current tests are broken correct me if I am wrong. 
for example:
https://github.com/change/cookie-dough/blob/master/test/index.js#L3

the test is trying to test the server src instead of browser.js. 

even if we did change it to:

``` javascript
subject = require('../browser.js')()
```

the test will still fail in node since document ain't there.

I am also not sure what exactly we are testing in the server.js. 

I think we can start a PR for a refactoring of how tests are written and ran.

**Comment by goldensunliu** [comment]
@saponifi3d is it cook to merge for now?

**Comment by saponifi3d** [comment]
@goldensunliu running into a bit of a snafu with github org settings, will update when that is fixed. thanks again for the contrib :)

**Comment by goldensunliu** [comment]
No problem.
Josh Callender notifications@github.com于2016年5月6日 周五下午7:55写道：

**Comment by goldensunliu** [comment]
@saponifi3d any update on the merge?

**Comment by saponifi3d** [comment]
Was able to merge - updated to version 0.1.0. Thanks for the contrib, sorry it was so long to merge this :(

**Pull request merged**
